# Generated by Django 4.2.28 on 2026-02-27 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
